### PR TITLE
Fixes #146: Avoid using exceptions for flow control in JsonObject implementation

### LINKED ISSUE #146: Reference implementation shouldn't use exception handling for conditional logic
I noticed code like the following in JsonObjectBuilderImpl.java
```
        @Override
        public String getString(String name, String defaultValue) {
            try {
                return getString(name);
            } catch (Exception e) {
                return defaultValue;
            }
        }
```
It is using exception handling to return the default value in cases where the entry is not present or not a string.  This is not good practice and can be a performance bottleneck as the stack trace is constructed and discarded.   Instead, the code should use a null check on the raw value followed by a check on its value kind if it is not null.

### PR DESCRIPTION
**Pull request by jhinch-at-atlassian-com**
Exceptions by default will fill stacktraces which is very expensive
particularly when performed in a tight loop or in places with deep
stacks (such as on webservers). Replace there use within the variants
of getString, getInt and getBoolean which apply a default value. The
two exceptions which could previously be thrown were null pointers and
class cast which are now both handled using an instanceof check

Bug: https://github.com/eclipse-ee4j/jsonp/issues/146

### CODE REVIEW

**Comment by jhinch-at-atlassian-com** [comment]
It seems like the JDK8 build might be having some infrastructure related issues. It doesn't seem related to my changes.

**Comment by leadpony** [comment]
The failure is due to the problem of Travis CI.
Travis uses `install-jdk.sh` available at https://github.com/sormuras/bach/blob/master/install-jdk.sh.
The script has dropped the support of Oracle JDK and now supports only OpenJDK 9 and higher.

**Comment by jjspiegel** [comment]
Looks good to me, thanks.

**Comment by jhinch-at-atlassian-com** [comment]
I have rebased my changes onto master. Both builds are now green, the changes are identical. Let me know if there is anything else you want me to do.

**Comment by jhinch-at-atlassian-com** [comment]
I have updated the copyright years as requested

File: impl/src/main/java/org/glassfish/json/JsonObjectBuilderImpl.java [hunk 1]
```diff
@@ -235,9 +235,10 @@ public String getString(String name) {
 
         @Override
         public String getString(String name, String defaultValue) {
-            try {
-                return getString(name);
-            } catch (Exception e) {
+            JsonValue value = get(name);
+            if (value instanceof JsonString) {
```
Comment (lukasj) [inline impl/src/main/java/org/glassfish/json/JsonObjectBuilderImpl.java]: why is this better than `if (value.getValueType() == ValueType.STRING)` ? just asking...

Comment (jjspiegel) [reply impl/src/main/java/org/glassfish/json/JsonObjectBuilderImpl.java]: I think they are functionally equivalent but your version would also need a null check:

`if (value == null && value.getValueType() == ValueType.STRING)`

I typically avoid instanceof for performance reasons.  But my understanding that this may be old fashioned as the performance of instanceof these days is good.   But I haven't tested it.

Comment (jhinch-at-atlassian-com) [reply impl/src/main/java/org/glassfish/json/JsonObjectBuilderImpl.java]: My understanding is that instanceof is sufficiently fast (as in, it is incredibly unlikely to show up as a hot spot in your profile), but if you would prefer `value != null && value.getValueType() == ValueType.STRING` I would be happy to change to that.

Comment (lukasj) [reply impl/src/main/java/org/glassfish/json/JsonObjectBuilderImpl.java]: makes sense, thanks for summing it up!
